### ISSUE TITLE
New build 2.0.1?

### ISSUE THREAD

**Issue by jvandijk** [ricardoalcocer/actionbarextras#126]
Hello @manumaticx,

Are you able to add a new distribution for the latest fix that was merged? I tried to build it myself but somehow the build process keeps hanging on 'packaging...' with my setup.

Thanks!

**Comment by manumaticx** [comment]
Hi.
I've put it on my list. The build setup for this module is still based on the `ant` way like in Titanium 4.x. So building with `appc` CLI doesn't work. We need to migrate the module structure to 7.0

**Comment by manumaticx** [comment]
Okay. Found the actual problem is some deprecation within the code. Working on a fix.

**Comment by manumaticx** [comment]
Still not able to build it. giving it up for now :(

**Comment by jvandijk** [comment]
How can I help here?

**Comment by manumaticx** [comment]
Maybe you can find out why the packaging is hanging?

I thought the problem may be that the javac isn't running correctly - I also tried building with `ant` again with 6.2.0 but no success.

Also stumbled upon this bug: https://jira.appcelerator.org/browse/TIMOB-25973

Any idea?

**Comment by kbshl** [comment]
Hey @manumaticx,

I've also tried to build the module on my machine for the last two days. Finally I figured it out:  

The `documentation/header.png` image causes the hanging of the `appc run -p android --build-only` command.

If you move the structure to the new module boilerplate and update the config files, remove the header.png from the documentation folder. Afterwards the build should be running fine with `appc run -p android --build-only`. 

I've tested it by fetching the actual repo, moved to the new module structure, adjusted the config files and build it. So I didn't change any code. 

I've attached my config files and the module structure of my setup, maybe it will help you.

[config-files.zip (.classpath, manifest, timodule.xml, build.properties, build.xml)](https://github.com/ricardoalcocer/actionbarextras/files/2205897/config-files.zip)

![module-structure](https://user-images.githubusercontent.com/4501298/42883995-6bfdf836-8a9d-11e8-87a4-c0b46cad40cd.jpg)

Honestly I didn't tested the compiled module yet. This will be my next step.

**Comment by manumaticx** [comment]
Wow! Thank you so much 🙏 @kbshl 

I had no idea this could be the problem! I'll try and push a new release asap

**Comment by jvandijk** [comment]
For reference... this is the issue, fixed in TiSDK 7.3.0, https://jira.appcelerator.org/browse/TIMOB-25418

**Comment by manumaticx** [comment]
fyi: my setup is still broken. hans committed a new build here:
https://github.com/ricardoalcocer/actionbarextras/blob/master/dist/com.alcoapps.actionbarextras-android-2.0.1.zip
